/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an analysis
         * @description Starts a run and returns immediately with a stream URL.
         *
         *     A full analysis takes 60-120 seconds across four stages, so the work
         *     happens in the background and progress arrives over the SSE endpoint.
         */
        post: operations["create_analysis_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Analysis */
        get: operations["stream_analysis_v1_analyses__analysis_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate a report
         * @description Useful / not useful on a report.
         *
         *     Closes the gap left by Phase 1: the API contract listed this endpoint but
         *     it was never built, so the UI had nothing to call.
         */
        post: operations["submit_feedback_v1_analyses__analysis_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{analysis_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint a public read-only link for a report */
        post: operations["create_share_token_v1_analyses__analysis_id__share_post"];
        /** Revoke a report's public link */
        delete: operations["revoke_share_token_v1_analyses__analysis_id__share_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record willingness to pay at the price shown */
        post: operations["record_pay_intent_v1_billing_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reliability of PMIE's own confidence scores */
        get: operations["calibration_v1_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a product event (UI mode switch, analysis started) */
        post: operations["record_event_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Answers as soon as the process is up. Public: load balancers cannot
         *     authenticate.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interests/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Selectable market categories
         * @description The selectable categories.
         *
         *     Served from the database rather than hardcoded in the client so the list
         *     and its labels have one source of truth.
         */
        get: operations["interest_categories_v1_interests_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/moving": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markets moving now, in the user's categories */
        get: operations["moving_markets_v1_markets_moving_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description The caller's profile, interests and usage.
         *
         *     One call so the client can render the whole authenticated shell — header,
         *     usage indicator, onboarding state — without a waterfall of requests.
         */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose 3-5 interest categories */
        put: operations["set_interests_v1_me_interests_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether TOTP is active for this user */
        get: operations["mfa_status_v1_me_mfa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/mfa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin TOTP enrolment */
        post: operations["enroll_mfa_v1_me_mfa_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a TOTP code and activate the factor */
        post: operations["verify_mfa_v1_me_mfa_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This user's referral code and its standing */
        get: operations["referrals_v1_me_referrals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Reports whether this process can do its job, not merely that it is up.
         *
         *     Distinct from /health on purpose: a server that cannot persist reports
         *     answers /health perfectly well while silently discarding the only data
         *     the product's claims rest on.
         */
        get: operations["ready_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join the beta waitlist (public) */
        post: operations["join_waitlist_v1_waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisCreated */
        AnalysisCreated: {
            /** Analysis Id */
            analysis_id: string;
            /** Status */
            status: string;
            /** Stream Url */
            stream_url: string;
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Query */
            query: string;
            /** Slug */
            slug?: string | null;
        };
        /** AnalysisResult */
        AnalysisResult: {
            /** Analysis Id */
            analysis_id: string;
            /** Error */
            error?: string | null;
            report?: components["schemas"]["MarketAnalysisReport"] | null;
            /** Status */
            status: string;
        };
        /**
         * CalibrationBin
         * @description One point on the reliability curve.
         */
        CalibrationBin: {
            /** Lower */
            lower: number;
            /**
             * Observed Accuracy
             * @description Share that held up at 48h.
             */
            observed_accuracy: number;
            /** Sample Size */
            sample_size: number;
            /**
             * Stated Confidence
             * @description Mean confidence claimed in this bin.
             */
            stated_confidence: number;
            /** Upper */
            upper: number;
        };
        /**
         * CalibrationResponse
         * @description Explanation calibration — NOT a forecast record.
         *
         *     This answers "when PMIE says 0.7, is it right about 70% of the time?" It
         *     does not score predictions of market outcomes, because PMIE does not make
         *     any. `sufficient` gates display: a curve drawn from a handful of reports
         *     misleads, so the UI shows a collecting state until there is enough.
         */
        CalibrationResponse: {
            /** Bins */
            bins: components["schemas"]["CalibrationBin"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Minimum For Display */
            minimum_for_display: number;
            /** Sufficient */
            sufficient: boolean;
            /** Total Scored */
            total_scored: number;
        };
        /** CategoriesResponse */
        CategoriesResponse: {
            /** Categories */
            categories: components["schemas"]["InterestCategory"][];
        };
        /**
         * CausalDriver
         * @enum {string}
         */
        CausalDriver: "WHALE_ACTIVITY" | "VOLUME_SPIKE" | "LIQUIDITY_CRUNCH" | "EXTERNAL_NEWS" | "UNKNOWN_ANOMALY";
        /**
         * CitedSource
         * @description One item of evidence, with its provenance and its bearing on the cause.
         *
         *     A CONTRADICTS entry is a feature, not a failure: showing the evidence that
         *     cuts against the conclusion is what makes the confidence score legible.
         */
        CitedSource: {
            /** Published At */
            published_at?: string | null;
            /** Publisher */
            publisher: string;
            tier: components["schemas"]["SourceTier"];
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            verification: components["schemas"]["ClaimVerification"];
        };
        /**
         * ClaimVerification
         * @description Whether a citation bears on the stated cause — not whether it is true.
         * @enum {string}
         */
        ClaimVerification: "SUPPORTS" | "CONTRADICTS" | "UNSUPPORTED";
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Is Useful */
            is_useful: boolean;
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service?: string | null;
            /** Status */
            status: string;
        };
        /** HistoricalContextMatch */
        HistoricalContextMatch: {
            /** Previous Market Id */
            previous_market_id: string;
            /** Prior Explanation Accuracy */
            prior_explanation_accuracy: number;
        };
        /**
         * Impact
         * @enum {string}
         */
        Impact: "HIGH" | "MEDIUM" | "LOW";
        /** InterestCategory */
        InterestCategory: {
            /** Description */
            description?: string | null;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** InterestsRequest */
        InterestsRequest: {
            /** Categories */
            categories: string[];
        };
        /** InterestsResponse */
        InterestsResponse: {
            /** Interests */
            interests: string[];
        };
        /** KeyDriver */
        KeyDriver: {
            /** Evidence Summary */
            evidence_summary: string;
            impact: components["schemas"]["Impact"];
            /** Type */
            type: string;
        };
        /** MarketAnalysisReport */
        MarketAnalysisReport: {
            /**
             * Cited Sources
             * @default []
             */
            cited_sources: components["schemas"]["CitedSource"][];
            /** Confidence Score */
            confidence_score: number;
            historical_context_match?: components["schemas"]["HistoricalContextMatch"] | null;
            /** Key Drivers */
            key_drivers: components["schemas"]["KeyDriver"][];
            /** Market Id */
            market_id: string;
            primary_causal_driver: components["schemas"]["CausalDriver"];
            /** @default POLYMARKET */
            source: components["schemas"]["MarketSource"];
            /** Summary */
            summary: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * MarketSource
         * @enum {string}
         */
        MarketSource: "POLYMARKET" | "KALSHI";
        /** MeResponse */
        MeResponse: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Id */
            id: string;
            /** Interests */
            interests: string[];
            /** Is Grandfathered */
            is_grandfathered: boolean;
            /** Is Invited */
            is_invited: boolean;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            usage: components["schemas"]["UsageSummary"];
        };
        /**
         * MfaEnrollResponse
         * @description TOTP enrollment. The secret is shown exactly once.
         */
        MfaEnrollResponse: {
            /** Factor Id */
            factor_id: string;
            /**
             * Qr Uri
             * @description otpauth:// URI for a QR code.
             */
            qr_uri: string;
            /**
             * Recovery Codes
             * @description Single-use fallbacks. Shown once, stored hashed.
             */
            recovery_codes: string[];
            /**
             * Secret
             * @description Base32 TOTP secret. Never returned again.
             */
            secret: string;
        };
        /** MfaStatusResponse */
        MfaStatusResponse: {
            /** Enrolled */
            enrolled: boolean;
            /** Verified At */
            verified_at?: string | null;
        };
        /** MfaVerifyRequest */
        MfaVerifyRequest: {
            /** Code */
            code: string;
            /** Factor Id */
            factor_id: string;
        };
        /** MovingMarket */
        MovingMarket: {
            /** Category */
            category: string;
            /** Change 24H */
            change_24h: number;
            /** Days To Resolution */
            days_to_resolution?: number | null;
            /** Probability */
            probability: number;
            /** Question */
            question: string;
            /** Slug */
            slug: string;
            /**
             * Source
             * @description POLYMARKET or KALSHI.
             */
            source: string;
            /** Volume 24H */
            volume_24h: number;
        };
        /**
         * MovingMarketsResponse
         * @description The personalised feed — ranked by movement, not popularity (UI_PRD 6.4).
         */
        MovingMarketsResponse: {
            /**
             * Categories
             * @description Categories this feed was built from.
             */
            categories: string[];
            /** Markets */
            markets: components["schemas"]["MovingMarket"][];
        };
        /**
         * PayIntentRequest
         * @description A click on the quota wall, not a payment.
         *
         *     No money moves during beta. This records that someone who had used the
         *     product wanted more of it at a stated price, which is the signal the beta
         *     exists to collect.
         */
        PayIntentRequest: {
            /**
             * Plan
             * @description Plan label shown, e.g. 'pro-monthly'.
             */
            plan: string;
            /**
             * Price Shown Usd
             * @description The price on screen.
             */
            price_shown_usd: number;
        };
        /**
         * ProblemResponse
         * @description RFC 9457 problem+json.
         *
         *     Declared so the documented error shape matches what the API actually
         *     returns; clients switch on `type`, never on `title` or `detail`.
         */
        ProblemResponse: {
            /** Detail */
            detail: string;
            /** Instance */
            instance?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** ReadyChecks */
        ReadyChecks: {
            /** Detail */
            detail?: string | null;
            /** Report Store Writable */
            report_store_writable: string;
        };
        /** ReadyResponse */
        ReadyResponse: {
            checks: components["schemas"]["ReadyChecks"];
            /** Service */
            service?: string | null;
            /** Status */
            status: string;
        };
        /** ReferralSummary */
        ReferralSummary: {
            /** Analyses Granted */
            analyses_granted: number;
            /**
             * Code
             * @description This user's own referral code.
             */
            code: string;
            /**
             * Converted Count
             * @description Referrals that verified their email. Only these count.
             */
            converted_count: number;
            /**
             * Next Reward At
             * @description Converted referrals needed for the next grant.
             */
            next_reward_at: number;
            /** Referred Count */
            referred_count: number;
        };
        /** ShareTokenResponse */
        ShareTokenResponse: {
            /** Expires At */
            expires_at?: string | null;
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /**
         * SourceTier
         * @description How much weight a citation can carry on its own.
         * @enum {string}
         */
        SourceTier: "PRIMARY" | "PARTIAL" | "WEAK";
        /**
         * UiMode
         * @enum {string}
         */
        UiMode: "TERMINAL" | "CONVENTIONAL";
        /** UsageSummary */
        UsageSummary: {
            /** Analyses This Month */
            analyses_this_month: number;
            /**
             * Enforced
             * @default false
             */
            enforced: boolean;
            /** Free Monthly Allowance */
            free_monthly_allowance: number;
        };
        /**
         * UserEventRequest
         * @description Product telemetry. Never PII beyond the authenticated user id.
         */
        UserEventRequest: {
            /**
             * Name
             * @description e.g. 'ui_mode_switched', 'analysis_started'.
             */
            name: string;
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: string;
            };
            ui_mode?: components["schemas"]["UiMode"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaitlistRequest */
        WaitlistRequest: {
            /** Email */
            email: string;
            /** Referral Code */
            referral_code?: string | null;
        };
        /** WaitlistResponse */
        WaitlistResponse: {
            /**
             * Already Registered
             * @default false
             */
            already_registered: boolean;
            /**
             * Position
             * @description Null when positions are not disclosed.
             */
            position?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_analysis_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreated"];
                };
            };
            /** @description Not signed in, or the token failed verification */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Signed in but not invited to the alpha */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_analysis_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_analysis_v1_analyses__analysis_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events. One `stage_started` / `stage_completed` pair per pipeline stage (event_retrieval, signal_retrieval, news_retrieval, analysis), then a terminal `report` or `error` event. Each `data:` line is a JSON object `{stage, data}`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_v1_analyses__analysis_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in, or the token failed verification */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Signed in but not invited to the alpha */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    create_share_token_v1_analyses__analysis_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_share_token_v1_analyses__analysis_id__share_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    record_pay_intent_v1_billing_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    calibration_v1_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResponse"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    record_event_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    interest_categories_v1_interests_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    moving_markets_v1_markets_moving_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovingMarketsResponse"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not signed in, or the token failed verification */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Signed in but not invited to the alpha */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    set_interests_v1_me_interests_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterestsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestsResponse"];
                };
            };
            /** @description Not signed in, or the token failed verification */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Signed in but not invited to the alpha */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description Fewer than 3, more than 5, or unknown categories */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                    "application/problem+json": unknown;
                };
            };
        };
    };
    mfa_status_v1_me_mfa_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusResponse"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enroll_mfa_v1_me_mfa_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnrollResponse"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_mfa_v1_me_mfa_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    referrals_v1_me_referrals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralSummary"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    join_waitlist_v1_waitlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet — the contract is frozen, the logic is not. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
